# Generated by Django 4.1.5 on 2023-01-12 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('domain', models.CharField(max_length=30, unique=True)),
                ('file_storage_bytes_limit', models.PositiveBigIntegerField(default=2147483648)),
                ('number_of_files_limit', models.PositiveIntegerField(default=20)),
                ('organization_tier', models.CharField(choices=[('FREE', 'Free'), ('TEAM', 'Team'), ('ENTERPRISE', 'Enterprise')], default='FREE', max_length=10)),
            ],
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('organization_tier', 'FREE'), ('number_of_files_limit__lte', 20)), models.Q(('organization_tier', 'FREE'), _negated=True), _connector='OR'), name='organization_free_limitation_constraint'),
        ),
    ]
