# Generated by Django 4.1.5 on 2023-01-12 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_tier',
            field=models.CharField(choices=[('FREE', 'Free'), ('INDIVIDUAL', 'Individual'), ('TEAM', 'Team'), ('ENTERPRISE', 'Enterprise')], default='FREE', max_length=10),
        ),
    ]
